// <auto-generated />
using HManagementLead.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HManagementLead.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240213092438_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HManagementLead.Data.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("HManagementLead.Data.Enitites.LicitacionClientes", b =>
                {
                    b.Property<int>("Cliente_id")
                        .HasColumnType("int");

                    b.Property<int>("Licitacion_id")
                        .HasColumnType("int");

                    b.HasKey("Cliente_id", "Licitacion_id");

                    b.HasIndex("Licitacion_id");

                    b.ToTable("LicitacionCliente");
                });

            modelBuilder.Entity("HManagementLead.Data.Enitites.LicitacionProyectos", b =>
                {
                    b.Property<int>("Proyecto_id")
                        .HasColumnType("int");

                    b.Property<int>("Licitacion_id")
                        .HasColumnType("int");

                    b.HasKey("Proyecto_id", "Licitacion_id");

                    b.HasIndex("Licitacion_id");

                    b.ToTable("LicitacionProyectos");
                });

            modelBuilder.Entity("HManagementLead.Data.Enitites.Licitaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Licitaciones");
                });

            modelBuilder.Entity("HManagementLead.Data.Enitites.SeguimientoClientes", b =>
                {
                    b.Property<int>("Cliente_id")
                        .HasColumnType("int");

                    b.Property<int>("Seguimiento_id")
                        .HasColumnType("int");

                    b.HasKey("Cliente_id", "Seguimiento_id");

                    b.HasIndex("Seguimiento_id");

                    b.ToTable("SeguimientoCliente");
                });

            modelBuilder.Entity("HManagementLead.Data.Enitites.SeguimientoProyectos", b =>
                {
                    b.Property<int>("Proyecto_id")
                        .HasColumnType("int");

                    b.Property<int>("Seguimiento_id")
                        .HasColumnType("int");

                    b.HasKey("Proyecto_id", "Seguimiento_id");

                    b.HasIndex("Seguimiento_id");

                    b.ToTable("SeguimientoProyecto");
                });

            modelBuilder.Entity("HManagementLead.Data.Enitites.Seguimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Seguimientos");
                });

            modelBuilder.Entity("HManagementLead.Data.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cliente_id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cliente_id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("HManagementLead.Data.Enitites.LicitacionClientes", b =>
                {
                    b.HasOne("HManagementLead.Data.Cliente", "IdClienteNavigation")
                        .WithMany("Licitaciones")
                        .HasForeignKey("Cliente_id")
                        .IsRequired()
                        .HasConstraintName("FK_LicitacionClientes_Clientes");

                    b.HasOne("HManagementLead.Data.Enitites.Licitaciones", "IdLicitacionNavigation")
                        .WithMany()
                        .HasForeignKey("Licitacion_id")
                        .IsRequired()
                        .HasConstraintName("FK_LicitacionClientes_Seguimientos");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdLicitacionNavigation");
                });

            modelBuilder.Entity("HManagementLead.Data.Enitites.LicitacionProyectos", b =>
                {
                    b.HasOne("HManagementLead.Data.Enitites.Licitaciones", "IdLicitacionNavigation")
                        .WithMany()
                        .HasForeignKey("Licitacion_id")
                        .IsRequired()
                        .HasConstraintName("FK_LicitacionProyectos_Seguimientos");

                    b.HasOne("HManagementLead.Data.Proyecto", "IdProyectoNavigation")
                        .WithMany("Licitaciones")
                        .HasForeignKey("Proyecto_id")
                        .IsRequired()
                        .HasConstraintName("FK_LicitacionProyectos_Proyectos");

                    b.Navigation("IdLicitacionNavigation");

                    b.Navigation("IdProyectoNavigation");
                });

            modelBuilder.Entity("HManagementLead.Data.Enitites.SeguimientoClientes", b =>
                {
                    b.HasOne("HManagementLead.Data.Cliente", "IdClienteNavigation")
                        .WithMany("Seguimientos")
                        .HasForeignKey("Cliente_id")
                        .IsRequired()
                        .HasConstraintName("FK_SeguimientosClientes_Clientes");

                    b.HasOne("HManagementLead.Data.Enitites.Seguimientos", "IdSeguimientoNavigation")
                        .WithMany()
                        .HasForeignKey("Seguimiento_id")
                        .IsRequired()
                        .HasConstraintName("FK_SeguimientosClientes_Seguimientos");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdSeguimientoNavigation");
                });

            modelBuilder.Entity("HManagementLead.Data.Enitites.SeguimientoProyectos", b =>
                {
                    b.HasOne("HManagementLead.Data.Proyecto", "IdProyectoNavigation")
                        .WithMany("Seguimientos")
                        .HasForeignKey("Proyecto_id")
                        .IsRequired()
                        .HasConstraintName("FK_SeguimientosProyectos_Proyectos");

                    b.HasOne("HManagementLead.Data.Enitites.Seguimientos", "IdSeguimientoNavigation")
                        .WithMany()
                        .HasForeignKey("Seguimiento_id")
                        .IsRequired()
                        .HasConstraintName("FK_SeguimientosProyectos_Seguimientos");

                    b.Navigation("IdProyectoNavigation");

                    b.Navigation("IdSeguimientoNavigation");
                });

            modelBuilder.Entity("HManagementLead.Data.Proyecto", b =>
                {
                    b.HasOne("HManagementLead.Data.Cliente", "IdClienteNavigation")
                        .WithMany("Proyectos")
                        .HasForeignKey("Cliente_id")
                        .IsRequired()
                        .HasConstraintName("FK_Proyectos_Clientes");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("HManagementLead.Data.Cliente", b =>
                {
                    b.Navigation("Licitaciones");

                    b.Navigation("Proyectos");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("HManagementLead.Data.Proyecto", b =>
                {
                    b.Navigation("Licitaciones");

                    b.Navigation("Seguimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
